services:
  mysqlocp:
    container_name: mysqlocp
    hostname: mysqlocp
    image: registry.cn-hangzhou.aliyuncs.com/redgreat/mysql_ocp:latest
    restart: unless-stopped
    ports:
      - "8094:80"
    environment:
      - TZ=Asia/Shanghai
      - DISABLE_IPV6=true
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
        resources:
          limits:
            memory: 1G
          reservations:
            memory: 8M
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"