version: '3.8'

services:
  mysql-practice-exam:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql-practice-exam
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 开发环境服务
  mysql-practice-exam-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mysql-practice-exam-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles:
      - dev